### ISSUE TITLE
Read credentials from Rails config file 

### ISSUE THREAD

**Issue by martin-mfv** [fog/fog-aws#705]
Currently, I want to create a `Fog` connection with params read from file `config/aws.yml`
For example: 

```yaml
default: &default
  aws_access_key: 
  aws_secret_key: 
  aws_region:  
  aws_endpoint: 

development:
  <<: *default

production:
  <<: *default
```
Can that be supported?
